services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped

    container_name: rabbitmq
    hostname: rabbitmq-server

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  mailing_db:
    image: postgres:15-alpine
    restart: always

    # Must have own name
    container_name: ${MAILING_DB_CONTAINER}

    # Env variables, must be unique
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${MAILING_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${MAILING_DB_NAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    volumes:
      # This must be unique not to override other db's data
      # This must be hard coded
      - mailing_pgdata:/var/lib/postgresql/data
      - ../backend/mailing-service/init-db:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 64M

    # ports:
    #   # Left side must be unique
    #   - "$MAILING_DB_PORT:5432"

  mailing_app:
    image: fiveguys301/mailing:latest
    container_name: ${MAILING_APP_CONTAINER}
    environment:
      - MAILING_SERVICE_PORT=${MAILING_SERVICE_PORT}
      - MAILING_TCP_PORT=${MAILING_TCP_PORT}
      - MAILING_DB_CONTAINER=${MAILING_DB_CONTAINER}
      - INTERNAL_DB_PORT=${INTERNAL_DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAILING_DB_NAME=${MAILING_DB_NAME}
      - DB_SYNC=${DB_SYNC}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_EMAIL_DELIVERED=${RESEND_EMAIL_DELIVERED}
      - RESEND_EMAIL=${RESEND_EMAIL}
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - BUSINESS_NAME=${BUSINESS_NAME}
      - TRACKING_LINK=${TRACKING_LINK}

    # ports:
    #   - "${MAILING_SERVICE_PORT}:${MAILING_SERVICE_PORT}"

    depends_on:
      mailing_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    
  accounts_db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=${ACCOUNTS_DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${ACCOUNTS_DB_NAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    container_name: ${ACCOUNTS_DB_CONTAINER}
    volumes:
      - accounts_pgdata:/var/lib/postgresql/data
    # ports:
    #   - '${ACCOUNTS_DB_PORT}:5432'
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 64M
  
  accounts_app:
    image: fiveguys301/accounts:latest
    container_name: ${ACCOUNTS_APP_CONTAINER}
    environment:
      - PORT=${ACCOUNTS_SERVICE_PORT}
      - DB_HOST=${ACCOUNTS_DB_CONTAINER}
      - DB_PORT=${INTERNAL_DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${ACCOUNTS_DB_NAME}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_M2M_CLIENT_ID=${AUTH0_M2M_CLIENT_ID}
      - AUTH0_M2M_CLIENT_SECRET=${AUTH0_M2M_CLIENT_SECRET}
      - TCP_PORT=${ACCOUNTS_TCP_PORT}
      - MAILING_SERVICE_URL=http://${MAILING_APP_CONTAINER}:${MAILING_SERVICE_PORT}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_EMAIL_DELIVERED=${RESEND_EMAIL_DELIVERED}
      - RESEND_EMAIL=${RESEND_EMAIL}
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - NODE_ENV=dev
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_EMAIL_DELIVERED=${RESEND_EMAIL_DELIVERED}
      - RESEND_EMAIL=${RESEND_EMAIL}
      - RABBITMQ_URL=amqp://rabbitmq:5672
    # ports:
    #   - '${ACCOUNTS_SERVICE_PORT}:3002'
    depends_on:
      accounts_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M

  api_app:
    image: fiveguys301/api:latest
    restart: on-failure
    container_name: ${GATEWAY_APP_CONTAINER}
    environment:
      - VERSION=latest
      - OUR_EMAIL=${OUR_EMAIL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - API_GATEWAY_PORT=${API_GATEWAY_PORT}
      - ACCOUNTS_SERVICE_URL=http://${ACCOUNTS_APP_CONTAINER}:${ACCOUNTS_SERVICE_PORT}
      - MAILING_SERVICE_URL=http://${MAILING_APP_CONTAINER}:${MAILING_SERVICE_PORT}
      - XP_SERVICE_URL=http://${XP_APP_CONTAINER}:${XP_SERVICE_PORT}
      - REPORT_SERVICE_URL=http://${REPORT_APP_CONTAINER}:${REPORT_SERVICE_PORT}
      - EDUCATION_SERVICE_URL=http://${EDUCATION_APP_CONTAINER}:${EDUCATION_SERVICE_PORT}
      - ANALYTICS_SERVICE_URL=http://${ANALYTICS_APP_CONTAINER}:${ANALYTICS_SERVICE_PORT}
      - LLM_SERVICE_URL=http://${LLM_APP_CONTAINER}:${LLM_SERVICE_PORT}
      - COMPANY_SERVICE_URL=http://${COMPANY_APP_CONTAINER}:${COMPANY_SERVICE_PORT}
      - XP_HOST=${XP_APP_CONTAINER}
      - REPORT_HOST=${REPORT_APP_CONTAINER}
      - MAILING_HOST=${MAILING_APP_CONTAINER}
      - ACCOUNTS_HOST=${ACCOUNTS_APP_CONTAINER}
      - EDUCATION_HOST=${EDUCATION_APP_CONTAINER}
      - ANALYTICS_HOST=${ANALYTICS_APP_CONTAINER}
      - LLM_HOST=${LLM_APP_CONTAINER}
      - COMPANY_HOST=${COMPANY_APP_CONTAINER}
      - XP_TCP_PORT=${XP_TCP_PORT}
      - REPORT_TCP_PORT=${REPORT_TCP_PORT}
      - MAILING_TCP_PORT=${MAILING_TCP_PORT}
      - ACCOUNTS_TCP_PORT=${ACCOUNTS_TCP_PORT}
      - EDUCATION_TCP_PORT=${EDUCATION_TCP_PORT}
      - ANALYTICS_TCP_PORT=${ANALYTICS_TCP_PORT}
      - LLM_TCP_PORT=${LLM_TCP_PORT}
      - COMPANY_TCP_PORT=${COMPANY_TCP_PORT}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_M2M_CLIENT_ID=${AUTH0_M2M_CLIENT_ID}
      - AUTH0_M2M_CLIENT_SECRET=${AUTH0_M2M_CLIENT_SECRET}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - SERVER_DOMAIN=${DOMAIN}
      - OUTLOOK_ADDIN_CORS=
      - ENVIRONMENT=dev
      - LOG_DIR=/var/log/api-gateway
    # ports:
    #   - '${API_GATEWAY_PORT}:${API_GATEWAY_PORT}'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 384M
        reservations:
          cpus: '1.0'
          memory: 128M
  
  report_db:
    image: postgres:15-alpine
    restart: always
    container_name: ${REPORT_DB_CONTAINER}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${REPORT_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${REPORT_DB_NAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - report_pgdata:/var/lib/postgresql/data
    # ports:
    #   - "${REPORT_DB_PORT}:${INTERNAL_DB_PORT}"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 64M

  report_app:
    image: fiveguys301/report:latest
    container_name: ${REPORT_APP_CONTAINER}
    environment:
      - PORT=${REPORT_SERVICE_PORT}
      - TCP_PORT=${REPORT_TCP_PORT}
      - DB_HOST=${REPORT_DB_CONTAINER}
      - DB_PORT=${INTERNAL_DB_PORT}
      - DB_USERNAME=${DB_USERNAME}  
      - DB_PASSWORD=${DB_PASSWORD} 
      - DB_NAME=${REPORT_DB_NAME}  
      - AUTH0_DOMAIN=${AUTH0_DOMAIN} 
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE} 
      - REPORT_DB_PORT=${INTERNAL_DB_PORT}
      - RABBITMQ_URL=amqp://rabbitmq:5672
    # ports:
    #   - "${REPORT_SERVICE_PORT}:${REPORT_SERVICE_PORT}"
    depends_on:
      report_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 192M

  xp_db:
    image: postgres:15-alpine
    restart: always
    container_name: ${XP_DB_CONTAINER}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${XP_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${XP_DB_NAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - xp_pgdata:/var/lib/postgresql/data
    # ports:
    #   - "${XP_DB_PORT}:${INTERNAL_DB_PORT}"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 64M

  xp_app:
    image: fiveguys301/xp:latest
    container_name: ${XP_APP_CONTAINER}
    environment:
      - XP_SERVICE_PORT=${XP_SERVICE_PORT}
      - XP_TCP_PORT=${XP_TCP_PORT}
      - XP_DB_CONTAINER=${XP_DB_CONTAINER}
      - INTERNAL_DB_PORT=${INTERNAL_DB_PORT}
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - XP_DB_NAME=${XP_DB_NAME}
      - DB_SYNC=${DB_SYNC}
    # ports:
    #   - "${XP_SERVICE_PORT}:${XP_SERVICE_PORT}"
    depends_on:
      xp_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  education_db:
    image: postgres:15-alpine
    restart: always
    container_name: ${EDUCATION_DB_CONTAINER}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${EDUCATION_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${EDUCATION_DB_NAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - education_pgdata:/var/lib/postgresql/data
    # ports:
    #   - "${EDUCATION_DB_PORT}:${INTERNAL_DB_PORT}"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 192M
        reservations:
          cpus: '0.10'
          memory: 64M
      
  education_app:
    image: fiveguys301/education:latest
    container_name: ${EDUCATION_APP_CONTAINER}
    environment:
      - PORT=${EDUCATION_SERVICE_PORT}
      - TCP_PORT=${EDUCATION_TCP_PORT}
      - DB_HOST=${EDUCATION_DB_CONTAINER}
      - DB_PORT=${INTERNAL_DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${EDUCATION_DB_NAME}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - RABBITMQ_URL=amqp://rabbitmq:5672
    # ports:
    #   - "${EDUCATION_SERVICE_PORT}:${EDUCATION_SERVICE_PORT}"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 192M

    depends_on:
      education_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  analytics_db:
    image: postgres:15-alpine
    restart: always
    container_name: ${ANALYTICS_DB_CONTAINER}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${ANALYTICS_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${ANALYTICS_DB_NAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    volumes:
      - analytics_pgdata:/var/lib/postgresql/data

    # ports:
    #   - "${ANALYTICS_DB_PORT}:${INTERNAL_DB_PORT}"
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 64M
      
  analytics_app:
    image: fiveguys301/analytics:latest
    container_name: ${ANALYTICS_APP_CONTAINER}
    environment:
      - PORT=${ANALYTICS_SERVICE_PORT}
      - TCP_PORT=${ANALYTICS_TCP_PORT}
      - DB_HOST=${ANALYTICS_DB_CONTAINER}
      - DB_PORT=${INTERNAL_DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${ANALYTICS_DB_NAME}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - RABBITMQ_URL=amqp://rabbitmq:5672

    # ports:
    #   - "${ANALYTICS_SERVICE_PORT}:${ANALYTICS_SERVICE_PORT}"

    depends_on:
      analytics_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./src:/app/src
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: '256M'

  llm_db:
    image: postgres:15-alpine
    restart: always

    container_name: ${LLM_DB_CONTAINER}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${LLM_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${LLM_DB_NAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128M'
        reservations:
          cpus: '0.15'
          memory: 64M

    volumes:
      - llm_pgdata:/var/lib/postgresql/data

    ports:
      - "${LLM_DB_PORT}:${INTERNAL_DB_PORT}"
      
# Main service app container
  llm_app:
    image: fiveguys301/llm:latest
    container_name: ${LLM_APP_CONTAINER}
    environment:
      - PORT=${LLM_SERVICE_PORT}
      - TCP_PORT=${LLM_TCP_PORT}
      - DB_HOST=${LLM_DB_CONTAINER}
      - DB_PORT=${INTERNAL_DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${LLM_DB_NAME}
      - LLM_GATEWAY_URL=${LLM_GATEWAY_URL}
      - LLM_GATEWAY_KEY=${LLM_GATEWAY_KEY}
      - RABBITMQ_URL=amqp://rabbitmq:5672

    ports:
      - "${LLM_SERVICE_PORT}:${LLM_SERVICE_PORT}"

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128M'

    depends_on:
      llm_db:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  company_db:
    image: postgres:15-alpine
    restart: always

    container_name: ${COMPANY_DB_CONTAINER}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${COMPANY_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ${COMPANY_DB_NAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128M'
        reservations:
          cpus: '0.15'
          memory: 64M

    volumes:
      - company_pgdata:/var/lib/postgresql/data

    ports:
      - "${COMPANY_DB_PORT}:${INTERNAL_DB_PORT}"
      
# Main service app container
  company_app:
    image: fiveguys301/company:latest
    container_name: ${COMPANY_APP_CONTAINER}
    environment:
      - PORT=${COMPANY_SERVICE_PORT}
      - TCP_PORT=${COMPANY_TCP_PORT}
      - DB_HOST=${COMPANY_DB_CONTAINER}
      - DB_PORT=${INTERNAL_DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${COMPANY_DB_NAME}
      - RABBITMQ_URL=amqp://rabbitmq:5672

    ports:
      - "${COMPANY_SERVICE_PORT}:${COMPANY_SERVICE_PORT}"

    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '128M'

    depends_on:
      company_db:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  website:
    image: fiveguys301/website:latest
    restart: on-failure
    container_name: website
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 192M
  
  outlook_addin:
    image: fiveguys301/addin:latest
    restart: on-failure
    container_name: addin
    ports:
      - '3000:8080'
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 64M

  caddy:
    image: caddy:2.11.3
    container_name: caddy
    restart: unless-stopped
    ports: 
      - '127.0.0.1:8000:80'
      - '127.0.0.1:8001:443'
    volumes:
      - ./dev-caddy-conf:/etc/caddy/
      - caddy_logs:/var/log/caddy
      - caddy_data:/data
      - caddy_config:/config
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 32M
  
  watchtower:
    image: containrrr/watchtower:1.7.1
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: "3600"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_DEBUG: "true"
      DOCKER_API_VERSION: "1.40"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
    

volumes:
  # Must be same as volume name for db
  # Must be hard coded
  mailing_pgdata:
  accounts_pgdata:
  xp_pgdata:
  report_pgdata:
  education_pgdata:
  analytics_pgdata:
  llm_pgdata:
  company_pgdata:
  caddy_data:
  caddy_config:
  caddy_logs:
  rabbitmq_data:
    driver: local