services:
  ollama:
    image: ollama/ollama:0.33.3
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_NUM_PARALLEL=1
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '3G'
    networks:
      - local-llm

  ollama-pull-model:
    image: ollama/ollama:0.33.3
    container_name: ollama_pull_model
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    entrypoint: /bin/sh
    command: >
      -c "sleep 5 && ollama pull qwen2.5:1.5b"
    depends_on:
      - ollama
    networks:
      - local-llm
    

volumes:
  ollama_data:
    driver: local

networks:
  local-llm:
    external: true
    name: local-llm