-- AI was used to generate this temporary seeding data.
-- This is for testing purposes only
-- All data in this file was thoroughly reviewed
INSERT INTO emails ("id", "referenceNumber", "sender", "alias", "subject", "content", "difficulty", "createdAt")
VALUES
    ('970060d6-32e7-431d-9c9f-f4660b3d4e43',
     'PHISH-bee4270a',
     'no-reply@paypa1-security.com',
     'PayPal Security',
     'Your account has been limited',
     'We noticed unusual activity on your account. Click here within 24 hours to restore access or it will be permanently suspended: [Link]',
     'easy',
     NOW()),
    ('f0954139-d9b1-4a2f-8c0c-b1fb6fe93e30',
     'PHISH-a3f58acf',
     'winner-notify@intl-lottery-award.com',
     'International Lottery Commission',
     'CONGRATULATIONS!!! You have won R2,500,000',
     'Your email has been selected as the winner of our international lottery draw. Reply with your full name, address, and bank details to claim your R2,500,000 prize.',
     'easy',
     NOW()),
    ('82ddbdb7-8ef1-444a-82f6-61155db62a7a',
     'PHISH-1c2c7ff0',
     'it-helpdesk@company-support-portal.net',
     'IT Helpdesk',
     'Action required: Password expires today',
     'Your network password expires today. Verify your credentials now to avoid losing access: [Link]',
     'medium',
     NOW()s
     ),
    ('46cb766b-3dc8-4d14-a27f-64ac3dc8355d',
    'PHISH-f3100e0a',
    'billing@invoice-notify-service.com',
    'Accounts Payable',
    'Invoice #48213 overdue. Immediate payment required',
    'Invoice #48213 for R1,240.00 is overdue. Please remit payment within 48 hours to avoid late fees: [Link]',
    'medium',
    NOW()
    ),
    ('82460df6-366a-4a88-ac4a-ac0bb3363fe7',
    'PHISH-f72dde61',
    'delivery-alerts@parcel-track-update.com',
    'Courier Services',
    'We could not deliver your package',
    'We couldn''t deliver your package due to an incomplete address. Confirm your details to reschedule: [Link]',
    'medium',
    NOW()
    ),
    ('1c6c1302-a846-4234-8de7-2880b0ff70bc',
    'PHISH-5bc22f96',
    'ceo.office@yourcompany-exec.co',
    'Managing Director',
    'Quick task, are you available?',
    'I need you to handle something confidential before my meeting. Purchase gift cards for a client event and send me the codes.',
    'hard',
    NOW()
    ),
    ('39cc7dc2-d0e2-42e2-b51f-265691bc5bcd',
    'PHISH-694e2ab6',
    'hr@yourcompany-benefits-update.com',
    'Human Resources',
    'Updated benefits enrollment. Review by Friday!',
    'Please confirm your benefits enrollment by Friday using the portal below with your usual company credentials: [Link]',
    'hard',
    NOW()
    ),
    ('4749b7c7-bc74-4803-9904-d1c107547d02',
    'PHISH-352eedc5',
    'notifications@docusign-shared.net',
    'DocuSign',
    'Completed: Contract awaiting your signature',
    '"Vendor_Agreement_2024_Final.pdf" is waiting for your signature. This link expires in 24 hours: [Link]',
    'hard',
    NOW()
    ),
    ('94cc7df2-b8e4-42c0-9349-5902f472ff66',
    'PHISH-c27b2bd3',
    'newsletter@yourcompany.com',
    'Company Newsletter',
    'This month in review: team updates and wins',
    'Here''s a quick roundup of this month''s new hires, project milestones, and the quarterly innovation award winner.',
    'easy',
    NOW()
    ),
    ('53ab0b71-ce71-4f58-bd09-6075aef233a8',
    'PHISH-77133fbf',
    'support@microsft-office365.com',
    'Microsoft 365 Support',
    'Unusual sign-in activity detected',
    'We detected a sign-in from a new device in an unrecognized location. Secure your account now: [Link]',
    'medium',
    NOW()
    )
    ON CONFLICT ("referenceNumber")
    DO NOTHING;