services:
  app:
    build:
      context: ../../..
      dockerfile: project/backend/api-gateway/Dockerfile
    restart: on-failure
    container_name: ${GATEWAY_APP_CONTAINER}
    environment:
      - API_GATEWAY_PORT=3001
      - ACCOUNTS_SERVICE_URL=http://${ACCOUNTS_APP_CONTAINER}:3002
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    ports:
      - '${GATEWAY_PORT}:3001'
    networks:
      - accounts-service_backend  # joins the network accounts service created

networks:
  accounts-service_backend:
    external: true  # tells Docker this network already exists, don't create it