//This is the request body copied from: https://docs.llmgateway.io/v1_chat_completions
export interface LlmGatewayRequestBody {
  /**
   * @example `gpt-5`
   */
  model: string;
  messages: {
    /**
     * @example `user`
     */
    role: string;
    content?: /**
       * @example `Hello!`
       */
      | string
      | (
          | {
              type: 'text';
              text: string;
              cache_control?: { type: 'ephemeral'; ttl?: '5m' | '1h' };
              /**
               * OpenAI explicit prompt cache breakpoint marker (GPT-5.6 and later). Ends a cacheable prefix when the request sets prompt_cache_options.mode to 'explicit'. Stripped for providers/models without explicit prompt caching support.
               */
              prompt_cache_breakpoint?: { mode?: 'explicit' };
            }
          | {
              type: 'image_url';
              image_url: { url: string; detail?: 'low' | 'high' | 'auto' };
              prompt_cache_breakpoint?: { mode?: 'explicit' };
            }
          | {
              type: 'input_audio';
              input_audio: {
                data: string;
                format:
                  | 'wav'
                  | 'mp3'
                  | 'aiff'
                  | 'aac'
                  | 'ogg'
                  | 'flac'
                  | 'm4a'
                  | 'mpeg'
                  | 'mpga'
                  | 'mp4'
                  | 'pcm'
                  | 'webm';
              };
              prompt_cache_breakpoint?: { mode?: 'explicit' };
            }
          | {
              type: 'file';
              file: {
                filename?: string;
                /**
                 * Base64-encoded data URL with MIME prefix, e.g. 'data:application/pdf;base64,<data>'.
                 */
                file_data?: string;

                /**
                 * Reference to a file uploaded via the provider's Files API.
                 */
                file_id?: string;
              };
              prompt_cache_breakpoint?: { mode?: 'explicit' };
            }
        )[]
      | null;
    name?: string;
    tool_call_id?: string;
    /**
     * A list of tool calls generated by the model in this message.
     * @example
     * ```
     * [
     *   {
     *     "id": "call_abc123",
     *     "type": "function",
     *     "function": {
     *       "name": "get_current_weather",
     *       "arguments": "{\"location\": \"Boston, MA\"}"
     *     }
     *   }
     * ]
     * ```
     */
    tool_calls?: {
      id: string;
      type: 'function';
      function: { name: string; arguments: string };
    }[];
    reasoning?: string;
    reasoning_content?: string;
    reasoning_details?: { text?: string; type?: string }[];
    /**
     * OpenAI Responses assistant-message phase. Replayed upstream for OpenAI Responses API models; stripped for other providers.
     */
    phase?: 'commentary' | 'final_answer';

    /**
     * Marks assistant content that preceded the message's tool calls (pre-tool commentary on OpenAI Responses API models), so replay preserves the original item order. Stripped for other providers.
     */
    content_before_tool_calls?: boolean;

    /**
     * Separate phased assistant message items (e.g. commentary and final_answer) emitted by OpenAI Responses API models in a single turn. preceding_tool_calls records how many of the message's tool calls came before each item. Replayed upstream as individual message items in their original order; stripped for other providers.
     */
    message_items?: {
      text: string;
      phase?: 'commentary' | 'final_answer';
      /**
       * @minimum `0`
       */
      preceding_tool_calls?: number;
    }[];

    /**
     * Anthropic content blocks with no OpenAI-format equivalent. On an assistant message these are the server-side tool search blocks (`server_tool_use` + `tool_search_tool_result`), replayed ahead of the message's tool calls; on a tool message they are the `tool_result` content array, which is how a client-side tool search returns `tool_reference` blocks. Replayed on the Anthropic Messages API only and stripped for every other provider.
     */
    anthropic_native_blocks?: { type: string }[];
  }[];

  /**
   * @example `0.7`
   */
  temperature?: number | null;

  /**
   * @example `1000`
   */
  max_tokens?: number | null;

  /**
   * @example `0.9`
   */
  top_p?: number | null;

  /**
   * @example `0`
   */
  frequency_penalty?: number | null;

  /**
   * @example `0`
   */
  presence_penalty?: number | null;

  response_format?:
    | {
        /**
         * @example `json_object`
         */
        type: 'text' | 'json_object';
      }
    | {
        type: 'json_schema';
        json_schema: {
          name: string;
          description?: string;
          schema: Record<string, null>;
          strict?: boolean;
        };
      };

  /**
   * @default `false`
   */
  stream?: boolean;

  /**
   * How many chat completion choices to generate for each input message. Only accepted when the resolved model supports it upstream (currently OpenAI Chat Completions models and Google Gemini 2.5 models via `candidateCount`); requests for unsupported models are rejected with 400. Streaming is supported for OpenAI models: choice deltas are demultiplexed by `choices[].index` on a single SSE stream. Exceptions rejected with 400: `n > 1` with `stream: true` **and** function `tools` (the streaming tool-call aggregator can't disambiguate concurrent calls across choices; native `web_search` tools and the `web_search: true` flag are exempt), `n > 1` with `stream: true` on Google models (Gemini rejects candidateCount on streamGenerateContent), and `n > 8` on Google models (Gemini caps candidateCount at 8).
   * @minimum `1`
   * @maximum `128`
   * @example `1`
   */
  n?: number | null;

  /**
   * OpenAI prompt caching key used to improve cache routing for requests with shared prompt prefixes.
   * @example `tenant-123`
   */
  prompt_cache_key?: string | null;

  /**
   * OpenAI prompt cache retention policy. OpenAI supports in_memory and 24h for eligible models.
   * @example `24h`
   */
  prompt_cache_retention?: 'in_memory' | '24h';

  /**
   * OpenAI explicit prompt caching options (GPT-5.6 and later). mode 'implicit' (default) places an automatic cache breakpoint at the latest message; 'explicit' caches only content parts marked with prompt_cache_breakpoint. Only forwarded for OpenAI models that support explicit prompt caching.
   * @example
   * ```
   * {
   *   "mode": "explicit"
   * }
   * ```
   */
  prompt_cache_options?: { mode?: 'implicit' | 'explicit'; ttl?: '30m' } | null;

  /**
   * OpenAI end-user identifier. Used as a fallback sticky-routing session key when no x-session-id header or prompt_cache_key is provided.
   * @example `user-123`
   */
  user?: string | null;

  tools?: (
    | {
        type: 'function';
        function: {
          name: string;
          description?: string;
          parameters?: Record<string, null>;
        };

        /**
         * Anthropic only. Keeps the tool out of the rendered tools section so it never enters the cached prompt prefix, and loads it on demand once the tool search tool discovers it. Requires a `tool_search` tool in `tools`, and Anthropic rejects a request whose tools are all deferred. Stripped for every other provider, which receives the tool eagerly instead.
         */
        defer_loading?: boolean;
      }
    | {
        type: 'tool_search';
        /**
         * Anthropic tool search tool type, e.g. `tool_search_tool_regex_20251119` or `tool_search_tool_bm25_20251119`.
         * @pattern `^tool_search_tool`
         */
        tool_search_type: string;
        name?: string;
      }
    | {
        type: 'web_search';
        user_location?: {
          city?: string;
          region?: string;
          country?: string;
          timezone?: string;
        };
        search_context_size?: 'low' | 'medium' | 'high';
        max_uses?: number;
        allowed_domains?: string[];
        blocked_domains?: string[];
      }
  )[];

  /**
   * Controls which tool the model calls. `{"type": "web_search"}` demands a search instead of offering one, and requires a `web_search` tool in `tools`. Providers whose web search is model-elected are unaffected by it — the model already decides — but it is the only way to reach providers that can search solely on demand (currently Alibaba's DashScope and its resellers), which are otherwise skipped when routing a web search request.
   */
  tool_choice?:
    | 'auto'
    | 'none'
    | 'required'
    | { type: 'function'; function: { name: string } }
    | { type: 'web_search' };

  /**
   * Controls the reasoning effort for reasoning-capable models. `none` is only supported by OpenAI's newer reasoning models (e.g. gpt-5.4 and later); for other providers it disables reasoning. `max` is the highest tier (above `xhigh`), supported by Anthropic models and OpenAI GPT-5.6 models. The gateway never downgrades effort tiers: providers that accept an effort parameter receive the value unchanged (an unsupported value results in a provider error), while providers that take a thinking budget instead (e.g. Anthropic, Google) translate each tier to a native budget. The exact values each provider mapping accepts are exposed as `reasoning_efforts` on `/v1/models`.
   * @example `medium`
   */
  reasoning_effort?:
    | 'none'
    | 'minimal'
    | 'low'
    | 'medium'
    | 'high'
    | 'xhigh'
    | 'max';

  /**
   * Unified reasoning configuration object for controlling reasoning behavior
   */
  reasoning?: {
    /**
     * Controls the reasoning effort. Alternative to top-level reasoning_effort. Cannot be used together with reasoning_effort. `max` is the highest tier (above `xhigh`), supported by Anthropic models and OpenAI GPT-5.6 models. Tiers are never downgraded by the gateway: enum-based providers receive the value unchanged (unsupported values result in a provider error), while budget-based providers (e.g. Anthropic, Google) translate the tier to a native thinking budget. See `reasoning_efforts` on `/v1/models` for the values each mapping accepts.
     * @example `medium`
     */
    effort?: 'none' | 'minimal' | 'low' | 'medium' | 'high' | 'xhigh' | 'max';

    /**
     * Exact number of tokens to allocate for reasoning. When specified, overrides effort. Supported by Anthropic and Google thinking models.
     * @exclusiveMinimum `0`
     * @example `4000`
     */
    max_tokens?: number;

    /**
     * How much replayed reasoning the model considers (OpenAI Responses API models only). Omitting the field is equivalent to 'auto'. Forwarded upstream as reasoning.context; ignored by other providers.
     * @example `current_turn`
     */
    context?: 'auto' | 'current_turn' | 'all_turns';
  };

  /**
   * Controls the computational effort for supported models (currently only claude-opus-4-5-20251101)
   * @example `medium`
   */
  effort?: 'low' | 'medium' | 'high';

  /**
   * Controls how detailed the model's responses are. Only supported by OpenAI GPT-5 and later models; requests to models without verbosity support return a 400 error.
   * @example `low`
   */
  verbosity?: 'low' | 'medium' | 'high';

  /**
   * Processing tier for the request. `flex` and `priority` are forwarded only for provider/model mappings that explicitly support the requested tier, such as supported OpenAI and Google mappings. `auto`/`default` use the standard on-demand tier. Unsupported tier requests return a 400 `unsupported_service_tier` error. On coding (dev) plans only `auto`, `default` and `flex` are allowed.
   * @example `flex`
   */
  service_tier?: 'auto' | 'default' | 'flex' | 'priority';

  /**
   * Provider selection strategy for model-id routing, named after the factor it optimizes. `auto` (default) uses the full weighted smart-routing score. `price`, `throughput`, and `latency` each give a 90% relative weight to that factor while keeping a small uptime weight so requests still fall back to other providers when the top pick has extremely bad uptime. `latency` only biases streaming requests. Combining `routing` with a specific provider prefix (e.g. `openai/gpt-4o`) returns a 400. On coding (dev) plans only `auto` and `price` are allowed.
   * @example `price`
   */
  routing?: 'auto' | 'price' | 'throughput' | 'latency';

  /**
   * When used with auto routing, only route to free models (models with zero input and output pricing)
   * @default `false`
   * @example `false`
   */
  free_models_only?: boolean;

  /**
   * Deprecated and ignored. This once skipped email verification for free model usage, but the flag is client-supplied, so any account could assert it. Onboarding is now recognized server-side by the API proxy; setting this grants nothing.
   * @default `false`
   * @deprecated
   * @example `false`
   */
  onboarding?: boolean;

  /**
   * When used with auto routing, exclude reasoning models from selection
   * @default `false`
   * @example `false`
   */
  no_reasoning?: boolean;
  sensitive_word_check?: { status: 'DISABLE' | 'ENABLE' };
  image_config?: {
    aspect_ratio?: string;
    image_size?: string;
    image_quality?: 'low' | 'medium' | 'high' | 'auto';
    n?: number;
    seed?: number;
  };

  /**
   * Enable native web search for models that support it. When enabled, the model can search the web for real-time information.
   * @default `false`
   * @example `true`
   */
  web_search?: boolean;

  /**
   * Plugins to enable for this request. Currently supported: response-healing (automatically repairs malformed JSON responses when using response_format)
   * @example
   * ```
   * [
   *   {
   *     "id": "response-healing"
   *   }
   * ]
   * ```
   */
  plugins?: {
    /**
     * Plugin identifier
     * @example `response-healing`
     */
    id: 'response-healing';
  }[];
}

//LLM gateway's OK response object copied from: https://docs.llmgateway.io/v1_chat_completions
export interface OkLlmGatewayResponse {
  id: string;
  object: string;
  created: number;
  model: string;
  choices: {
    index: number;
    message: {
      role: string;
      content: string | null;
      reasoning?: string | null;
      tool_calls?: {
        id: string;
        type: 'function';
        function: { name: string; arguments: string };
      }[];
      images?: { type: 'image_url'; image_url: { url: string } }[];
    };
    finish_reason: string;
  }[];

  usage: {
    prompt_tokens: number;
    completion_tokens: number;
    total_tokens: number;
    reasoning_tokens?: number;
    prompt_tokens_details?: {
      cached_tokens: number;
      cache_write_tokens?: number;
      cache_creation_tokens?: number;
      cache_creation?: {
        ephemeral_5m_input_tokens: number;
        ephemeral_1h_input_tokens: number;
      };
      audio_tokens?: number;
      video_tokens?: number;
    };

    completion_tokens_details?: {
      reasoning_tokens?: number;
      image_tokens?: number;
      audio_tokens?: number;
    };
    cost?: number | null;
    cost_details?: {
      upstream_inference_cost: number;
      upstream_inference_prompt_cost: number;
      upstream_inference_completions_cost: number;
      total_cost?: number | null;
      input_cost?: number | null;
      output_cost?: number | null;
      cached_input_cost?: number | null;
      cache_write_input_cost?: number | null;
      request_cost?: number | null;
      web_search_cost?: number | null;
      image_input_cost?: number | null;
      image_output_cost?: number | null;
      audio_input_cost?: number | null;
      data_storage_cost?: number | null;
    };
    info?: string;
  };

  metadata: {
    request_id: string;
    requested_model: string;
    requested_provider: string | null;
    used_model: string;
    used_provider: string;
    used_region?: string | null;
    underlying_used_model: string;
    log_id?: string;
    organization_id?: string;
    project_id?: string;
    discount?: number | null;
    /**
     * True when the response was replayed from the gateway response cache instead of being generated upstream. Omitted otherwise.
     */
    cached?: boolean;

    routing?: {
      provider: string;
      model: string;
      region?: string;
      status_code: number;
      error_type: string;
      succeeded: boolean;
      /**
       * Stable fingerprint of the provider credential this attempt was sent with. Use it together with credentialSource to tell attempts apart when a request rotated keys.
       */
      apiKeyHash?: string;

      /**
       * Whose provider credential served this attempt. `byok` is your organization's own provider key — the provider bills you directly and no credits are deducted. `platform` is an LLM Gateway credential, billed as credits. A hybrid-mode request whose own key fails falls back to `platform`, so both values can appear in one response.
       */
      credentialSource?: 'byok' | 'platform';

      /**
       * Id of your provider key that served this attempt. Set only when credentialSource is `byok`.
       */
      providerKeyId?: string;

      /**
       * Your provider key as it is named on the provider-keys page (its name, or its masked token when unnamed), so an attempt can be tied to a key without decoding the fingerprint. Set only when credentialSource is `byok`; LLM Gateway's own credentials are never described.
       */
      providerKeyLabel?: string;
      logId?: string;
    }[];
  };
}

//LLM gateway's error response object copied from: https://docs.llmgateway.io/v1_chat_completions
export interface ErrorLlmGatewayResponse extends Error {
  error: {
    message: string;
    type: string;
    param: string | null;
    code: string;
  };
}

export interface ChatDto {
  model: string;
  messages: [
    {
      role: string;
      content: string;
    },
  ];
}
