services:
  pgadmin:
    image: dpage/pgadmin4:9.15
    restart: always

    # Must be unique
    container_name: PGADMIN_CONTAINER

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'True'
      PGADMIN_SERVER_JSON_FILE: servers.json
      PGADMIN_REPLACE_SERVERS_ON_STARTUP: 'True'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json:ro
      - ./.pgpass:/var/lib/pgadmin/.pgpass:ro
    ports:
      - "5050:80"
    networks:
      - backend

volumes:
  pgadmin_data:

networks:
  backend:
    name: backend_network
    external: true
    driver: bridge