
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${ACCOUNTS_DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    container_name: ${ACCOUNTS_DB_CONTAINER}
    volumes:
      - accounts_pgdata:/var/lib/postgresql/data
    ports:
      - '${ACCOUNTS_DB_PORT}:5432'
    networks:
      - backend

  app:
    build:
      context: ../../..
      dockerfile: project/backend/accounts-service/Dockerfile
    container_name: ${ACCOUNTS_APP_CONTAINER}
    environment:
      - PORT=3002
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${ACCOUNTS_DB_NAME}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_M2M_CLIENT_ID=${AUTH0_M2M_CLIENT_ID}
      - AUTH0_M2M_CLIENT_SECRET=${AUTH0_M2M_CLIENT_SECRET}
    ports:
      - '${ACCOUNTS_SERVICE_PORT}:3002'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - backend

networks:
  backend:
    name: backend_network
    external: true
    driver: bridge

volumes:
  accounts_pgdata: