name: backend CI

on:
  push:
    branches: [main, dev, backend]
  pull_request:
    branches: [main, dev]

jobs:
    API-Gateway-checks:
        name: API-Gateway Backend CI
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            - uses: pnpm/action-setup@fe0e12911100913926830ef529949646b9787e91  # v4.3.0
              with:
                version: 10.33.4
            - name: Install dependencies
              working-directory: ./Project/Backend/API-Gateway
              run: pnpm install --frozen-lockfile
            - name: test
              working-directory: ./Project/Backend/API-Gateway
              run: pnpm run test
            - name: lint
              working-directory: ./Project/Backend/API-Gateway
              run: pnpm run lint
            - name: build
              working-directory: ./Project/Backend/API-Gateway
              run: pnpm run build