name: build-docker-images

on:
    workflow_call:

jobs:
    build-and-push:
        runs-on: ubuntu-24.04
        strategy:
          matrix:
            include:
              - image: accounts
                dockerfile: ./project/backend/accounts-service/Dockerfile

              - image: api
                dockerfile: ./project/backend/api-gateway/Dockerfile
              
              - image: mailing
                dockerfile: ./project/backend/mailing-service/Dockerfile
              
              - image: report
                dockerfile: ./project/backend/report-service/Dockerfile

              - image: xp
                dockerfile: ./project/backend/xp-service/Dockerfile

              - image: analytics
                dockerfile: ./project/backend/analytics-service/Dockerfile
              
              - image: education
                dockerfile: ./project/backend/education-service/Dockerfile
              
              - image: website
                dockerfile: ./project/frontend/website/Dockerfile
        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            - name: login to  Docker Hub
              uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee #v4.2.0
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 #v4.1.0
            
            - name: Build and push ${{ matrix.image }}
              uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f #v7.1.0
              with:
                push: true
                context: .
                file: ${{ matrix.dockerfile }}
                tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.image }}:latest

    build-and-push-addin:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

            - name: login to  Docker Hub
              uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee #v4.2.0
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 #v4.1.0
            
            - name: Build and push
              uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f #v7.1.0
              with:
                push: true
                context: .
                file: ./project/frontend/phishshield-outlook-addin/Dockerfile
                tags: ${{ vars.DOCKERHUB_USERNAME }}/addin:latest
                build-args: |
                  API_BASE=${{ vars.PRODUCTION_API_BASE }}
                  ADDIN_BASE_URL=${{ vars.PRODUCTION_ADDIN_BASE_URL }}